### ISSUE TITLE
Rename Mainflux to Magistrala  in HELM charts

### ISSUE THREAD

**Issue by JeffMboya** [absmach/devops#130]
### 1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the existing issue, otherwise proceed to step 2.
No

### 2. Describe the enhancement you are requesting, as well as the possible use case(s) for it.
Rename "Mainflux" to "Magistrala" in HELM charts. This will make the naming more consistent.

### 3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must-have.

**Comment by dborovcanin** [comment]
It was resolved in the linked PR.
